FROM archlinux:latest
ARG TAGS
WORKDIR /usr/local/bin
ARG DEBIAN_FRONTEND=noninteractive
RUN pacman -Sy --noconfirm && pacman -S --noconfirm ansible curl git base-devel
COPY ansible/debian/local.yml /usr/local/bin/local.yml
COPY . .
CMD ["sh", "-c", "ansible-playbook $TAGS local.yml"]
