- hosts: localhost
  vars:
    user: "alex"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/brave.yml
    - include: tasks/dbaver.yml
    - include: tasks/discord.yml
    - include: tasks/postman.yml
    - include: tasks/slack.yml
    - include: tasks/vscode.yml
    - include: tasks/fonts.yml
    - include: tasks/docker.yml