- hosts: localhost
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/brave.yml
    - include: tasks/dbaver.yml
    - include: task/discord.yml
    - include: task/postman.yml
    - include: task/slack.yml
    - include: task/vscode.yml