- hosts: localhost
  vars:
    user: "alex"
    home: "/home/{{ user }}"
    source_key: "./.ssh"
    dest_key: "{{ home }}/.ssh"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/dbaver.yml
    - import_tasks: tasks/discord.yml
    - import_tasks: tasks/postman.yml
    - import_tasks: tasks/slack.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/docker-compose-setup.yml