
- name: Download Discord
  get_url:
    url: https://dl.discordapp.net/apps/linux/0.0.21/discord-0.0.21.deb
    dest: /tmp/discord.deb
  tags: &tags_for_discord_tasks ["discord"]

- name: Install Discord .deb package
  become: true
  apt:
    deb: /tmp/discord.deb
  tags: *tags_for_discord_tasks
