- name: Discord
  become: true
  tags: "discord"
  block:
    - name: Download Discord
      get_url:
        url: https://dl.discordapp.net/apps/linux/0.0.21/discord-0.0.21.deb
        dest: /tmp/discord.deb

    - name: Install Discord .deb package
      apt:
        deb: /tmp/discord.deb