- name: Docker
  become: true
  become_user: "{{ user }}"
  tasks:
  - name: Debug
    debug:
      msg: "{{ansible_env}}"
  # - name: Create docker directory
  #   file:
  #     path: /home/alex/.docker/cli-plugins
  #     state: directory

  # - name: Download docker-compose
  #   get_url:
  #     url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64
  #     dest: /home/alex/.docker/cli-plugins/docker-compose

  # - name: Set docker-compose permissions
  #   file:
  #     path: /home/alex/.docker/cli-plugins/docker-compose
  #     mode: 0755