- name: Docker
  become: true
  tags: "docker-compose"
  block:
    - name: Create docker directory
      file:
        path: "{{ home }}/.docker/cli-plugins"
        state: directory
    
    - name: Get docker-compose version
      shell: curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4
      register: docker_compose_version
      ignore_errors: true

    - name: Download docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-linux-x86_64
        dest: "{{ home }}/.docker/cli-plugins/docker-compose"

    - name: Set docker-compose permissions
      file:
        path: "{{ home }}/.docker/cli-plugins/docker-compose"
        mode: 0755