- name: Dotfiles configuration
  tags: "dotfiles"
  become_user: "{{ user }}"
  block:
    - name: Ensure scripts directory exists.
      file:
        dest: "{{ home }}/scripts"
        mode: 0777
        owner: "{{ user }}"
        group: "{{ user }}"
        state: directory

    - name: Clone bare repo
      git:
        repo: 'https://github.com/alexarevalo9/dotfiles.git'
        dest: "{{ home }}/.cfg"
        bare: true
    
    - name: Copy bash script
      copy:
        src: ./scripts/dotfiles.sh
        dest: "{{ home }}/scripts/dotfiles.sh"
        mode: 0777
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Run dotfiles script
      become: true
      shell: "bash {{ home }}/scripts/dotfiles.sh {{ home }}/.cfg {{ home }}"
      args:
        chdir: "{{ home }}"