- name: Required libraries Fonts
  become: true
  shell: add-apt-repository universe && apt-get update
  tags: &tags_for_fonts_tasks ["fonts"]

- name: Create fonts directory if it does not exist
  ansible.builtin.file:
    path: /.local/share/fonts
    state: directory
  tags: *tags_for_fonts_tasks

- name: Install FiraCode Font
  become: true
  apt:
    name: fonts-firacode
  tags: *tags_for_fonts_tasks

- name: Install Powerline Font
  become: true
  apt:
    name: fonts-powerline
  tags: *tags_for_fonts_tasks

- name: Download Meslo LG Regular Font
  become: true
  get_url:
    url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf
    dest: ~/.local/share/fonts
  tags: *tags_for_fonts_tasks

- name: Download Meslo NF Regular Font
  become: true
  get_url:
    url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/MesloLGS%20NF%20Regular.ttf
    dest: ~/.local/share/fonts
  tags: *tags_for_fonts_tasks

- name: Clear and Regenerate fonts
  shell: fc-cache -f -v
  tags: *tags_for_fonts_tasks