- name: Required libraries Fonts
  become: true
  shell: add-apt-repository universe && apt-get update && sudo mkdir ~/.local/share/fonts
  tags: &tags_for_fonts_tasks ["fonts"]

- name: Install FiraCode Font
  become: true
  apt:
    name: fonts-firacode
  tags: *tags_for_fonts_tasks

- name: Install Powerline Font
  become: true
  apt:
    name: fonts-powerline
  tags: *tags_for_fonts_tasks

- name: Download Meslo LG Regular Font
  get_url:
    url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf
    dest: ./Downloads/MesloLGMRegularNerdFontComplete.ttf
  tags: *tags_for_fonts_tasks

- name: Download Meslo NF Regular Font
  get_url:
    url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/MesloLGS%20NF%20Regular.ttf
    dest: ./Downloads/MesloLGSNFRegular.ttf
  tags: *tags_for_fonts_tasks

- name: Install Meslo Fonts
  become: true
  shell: mv ~/Downloads/MesloLGMRegularNerdFontComplete.ttf ~/.local/share/fonts/MesloLGMRegularNerdFontComplete.ttf && mv ~/Downloads/MesloLGSNFRegular.ttf ~/.local/share/fonts/MesloLGSNFRegular.ttf

- name: Clear and Regenerate fonts
  shell: fc-cache -f -v
  tags: *tags_for_fonts_tasks