- name: Fonts
  become: true
  tags: "fonts"
  block:
    - name: Required libraries Fonts
      shell: add-apt-repository universe && apt-get update

    - name: Create fonts directory if it does not exist
      file:
        path: /usr/share/fonts
        state: directory

    - name: Install FiraCode Font
      apt:
        name: fonts-firacode

    - name: Install Powerline Font
      apt:
        name: fonts-powerline

    - name: Download Meslo LG Regular Font
      get_url:
        url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/Meslo%20LG%20M%20Regular%20Nerd%20Font%20Complete.ttf
        dest: /usr/share/fonts

    - name: Download Meslo NF Regular Font
      get_url:
        url: https://github.com/alexarevalo9/ansible-setup-tools/raw/main/fonts/MesloLGS%20NF%20Regular.ttf
        dest: /usr/share/fonts

    - name: Clear and Regenerate fonts
      shell: fc-cache -f -v