- name: Node, npm & nvm
  become: true
  become_flags: -i
  become_user: alex
  tags: "node"
  block:
    - name: Install nodejs and npm
      apt:
        name: ["nodejs", "npm"]

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
    
    - name: Setup .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: Install node versions
      shell: >
        . $HOME/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/{{ item }}"
      loop:
          - '--lts'
          - 'v16.16.0'