- name: SSH configuration
  tags: "ssh"
  become: true
  block:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ dest_key }}"
        mode: 0777
        state: directory

    - name: Install personal ssh key
      copy:
        src: "{{ source_key }}/{{ item }}"
        dest: "{{ dest_key }}/{{ item }}"
        mode: 0777
      loop: 
        - id_rsa_personal
        - id_rsa_tinkin

    - name: Install personal ssh key public
      copy:
        src: "{{ source_key }}/{{ item }}.pub"
        dest: "{{ dest_key }}/{{ item }}.pub"
        mode: 0777
      loop: 
        - id_rsa_personal
        - id_rsa_tinkin

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ home }}/.ssh/{{ item }}.pub"
      with_fileglob:
      - "{{ home }}/.ssh/*.pub"
      loop: 
        - id_rsa_personal
        - id_rsa_tinkin
    
    - name: Move ssh config
      copy:
        src: "{{ source_key }}/config"
        dest: "{{ home }}/.ssh/config"
        mode: 0777